Current working directory
/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin
source venv/bin/activate
which python3
/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/bin/python3
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
INFO:preprocess_data_nn.py:

Loading and preprocessing data...

DEBUG:preprocess_data_nn.py:      date  permno
0  1980-01   10006
1  1980-01   10057
2  1980-01   10103
3  1980-01   10137
4  1980-01   10145
DEBUG:preprocess_data_nn.py:--------------------------------------------------
INFO:main.py:preprocessed df: (2216189, 158)
INFO:preprocess_data_nn.py:

Applying secondary data preprocessing..

INFO:main.py:secondary preprocessed df: (2165515, 158)
INFO:main.py:df sample:    permno  gvkey   adatadate  fyear  sic2     spi       mve_f  ...     zerotrade      beta    betasq      rsq1  pricedelay   idiovol  pyear
0   10006   1010  12/31/1978   1978    37  0.0000  269.308500  ...  1.115306e-07  1.060420  1.124491  0.343408    0.029859  0.025576   1980
1   10057   1098  09/30/1978   1978    36  0.0000   97.372000  ...  6.199128e-08  1.526013  2.328716  0.307905    0.092667  0.037473   1980
2   10103   1012  10/31/1978   1978    33     NaN    1.697500  ...           NaN  1.759493  3.095816  0.096753    0.221851  0.087020   1980
3   10137   1279  12/31/1978   1978    49     NaN  537.524500  ...  9.726790e-08  0.492885  0.242936  0.189693    0.125777  0.017540   1980
4   10145   1300  12/31/1978   1978    99 -0.0031  805.633282  ...  6.190654e-08  1.139163  1.297691  0.279437    0.024228  0.031201   1980

[5 rows x 158 columns]
INFO:main.py:

Transform data

INFO:transform_data_nn.py:Train data years: [1980, 1981, 1982, 1983, 1984, 1985, 1986]
INFO:transform_data_nn.py:Train_data: (341783, 158)

INFO:transform_data_nn.py:Test data years: [1987]
INFO:transform_data_nn.py:Test_data: (53899, 158)

INFO:transform_data_nn.py:Retrain data years: [1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987]
INFO:transform_data_nn.py:Retrain_data: (395682, 158)

INFO:transform_data_nn.py:Retrain data years: [1988]
INFO:transform_data_nn.py:Prediction_data: (56005, 158)

DEBUG:main.py:Pipeline built: Pipeline(steps=[('Time_period_mean_imputation',
                 _TimePeriodMeanTransformer(date_column='date',
                                            numeric_columns=['absacc', 'acc',
                                                             'aeavol', 'age',
                                                             'agr', 'baspread',
                                                             'beta', 'betasq',
                                                             'bm', 'bm_ia',
                                                             'cash', 'cashdebt',
                                                             'cashpr', 'cfp',
                                                             'cfp_ia',
                                                             'chatoia',
                                                             'chcsho',
                                                             'chempia',
                                                             'chfeps', 'chinv',
                                                             'chmom',
                                                             'chnanalyst',
                                                             'chpmia', 'chtx',
                                                             'cinvest',
                                                             'currat', 'depr',
                                                             'disp', 'dolvo...
                                                   'chempia', 'chfeps', 'chinv',
                                                   'chmom', 'chnanalyst',
                                                   'chpmia', 'chtx', 'cinvest',
                                                   'currat', 'depr', 'disp',
                                                   'dolvol', 'dy', ...]),
                                                 ('cat',
                                                  Pipeline(steps=[('impute_cat',
                                                                   SimpleImputer(fill_value=0,
                                                                                 strategy='constant'))]),
                                                  ['convind', 'divi', 'divo',
                                                   'ipo', 'rd', 'securedind',
                                                   'sin']),
                                                 ('embed',
                                                  Pipeline(steps=[('impute_embed',
                                                                   SimpleImputer(fill_value=0,
                                                                                 strategy='constant'))]),
                                                  ['permno'])]))])
INFO:main.py:

Generate X and y with train_data and test_data

DEBUG:main.py:Save the reload the tensors for much faster debugging
INFO:main.py:Tensors directory already exists at: /zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/tensors
DEBUG:main.py:Load the tensors
INFO:main.py:
        x_train_tf: torch.Size([341783, 103])
        y_train_tf: torch.Size([341783])

        x_test_tf: torch.Size([53899, 103])
        y_test_tf: torch.Size([53899])

    
INFO:main.py:
        x_retrain_tf: torch.Size([395682, 103])
        y_retrain_tf: torch.Size([395682])

        x_prediction_tf: torch.Size([56005, 103])
        y_prediction_tf: torch.Size([56005])

    
INFO:main.py:Create train_dataset
INFO:main.py:train_dataset first example: (tensor([ 0.2614,  0.5034,  0.2386, -0.6303,  0.0469, -0.5241, -0.0284, -0.2584,
         0.3866,  0.1910, -0.8830,  0.0062, -0.5088, -0.1862, -0.0053,  0.0250,
        -0.4235,  0.1175,  0.0000,  0.6719, -0.3586,  0.0000,  0.0257,  0.0166,
         0.0370, -0.2229, -0.6756,  0.0000,  0.5764,  1.1873,  0.6227, -0.1414,
         0.5064,  0.0000, -0.5226, -0.2165,  0.1496,  0.1907,  0.1020, -1.1512,
        -0.3211,  0.0239,  0.3191, -0.0440, -0.0208, -0.6509, -0.0216, -0.0993,
        -0.6609, -0.2278, -0.1547,  0.9190, -0.1748,  0.0000,  0.0265, -0.3809,
        -0.9466, -0.0875, -0.6362, -0.1616,  0.1008, -0.6415, -0.3684, -0.1993,
        -0.2698, -0.5237,  0.0996, -0.1018, -0.1900, -0.4132, -0.7240, -0.3249,
         0.0346, -0.8136,  0.1052, -1.0783,  0.2870,  0.2369,  0.6056,  0.1760,
        -0.4392, -0.2020, -0.0110,  0.0000, -0.0826, -0.0538, -0.3134, -0.6841,
        -0.4092, -0.4207,  0.1949, -0.2766,  0.1496, -0.1756, -0.5206,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]), tensor([5196]), tensor(0.2117))
INFO:main.py:Create test_dataset
INFO:main.py:test_dataset first example: (tensor([-6.9920e-03,  8.9557e-03, -3.4033e-01, -1.6683e+00,  4.0069e-03,
         1.0097e+00, -2.5891e-03, -1.0957e-02, -9.5448e-01,  1.8591e-01,
         3.8505e-01,  6.2086e-01,  1.9972e-01,  2.1500e-02, -2.2037e-05,
         6.4081e-03, -7.8682e-03,  1.2509e-02,  0.0000e+00,  2.2175e-02,
        -7.5173e-02,  0.0000e+00, -1.5533e-02,  1.2460e-02,  3.1036e-02,
         1.3005e-01, -2.3377e-01,  0.0000e+00, -4.6695e-01, -7.7328e-01,
        -6.6426e-01,  6.0568e-03, -1.6879e-02,  0.0000e+00,  1.5509e-02,
        -1.9876e-03,  9.2778e-03, -4.6920e-01,  6.8878e-04, -2.7767e-02,
        -1.1036e-01, -6.2118e-01,  1.3711e-02, -4.6129e-01, -4.5306e-03,
         2.2998e+00,  1.6293e-02, -1.3041e+00,  5.4224e-02, -1.1150e-03,
        -8.5550e-01, -1.1288e+00, -3.1813e-01,  0.0000e+00, -8.7597e-01,
         1.4499e-02,  3.0605e-02,  1.3658e-02, -8.7689e-03, -1.7061e-02,
         1.2506e-02, -1.1364e-02, -2.6022e-03,  1.5424e-03, -6.5274e-04,
        -7.4535e-03, -6.8802e-03, -2.2825e-02,  2.5533e-02,  1.5004e-01,
        -1.1726e-02, -2.4365e-02,  3.4575e-02,  1.6018e+00, -3.4779e+00,
        -7.2764e-02, -2.0625e+00,  4.1949e-01, -3.2436e-01, -4.6815e-01,
        -4.0800e-01, -3.1863e-01,  1.6746e+00,  0.0000e+00, -3.2632e-03,
        -6.4726e-01,  8.8510e-02,  5.2651e-01, -4.4860e-02, -4.4852e-02,
        -2.1688e-01,  1.4353e+00,  1.8772e-01,  3.0461e-01, -5.2065e-01,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
         1.0000e+00,  0.0000e+00]), tensor([3934]), tensor(-0.5200))
INFO:main.py:Create retrain_dataset
INFO:main.py:retrain_dataset first example: (tensor([ 2.4375e-01,  4.9617e-01,  2.3474e-01, -6.5108e-01,  3.9445e-02,
        -5.2971e-01, -3.2399e-02, -2.6454e-01,  4.4939e-01,  1.9404e-01,
        -8.7559e-01,  2.9982e-02, -5.1678e-01, -1.7870e-01,  2.8057e-02,
         2.6105e-02, -4.2786e-01,  1.3802e-01,  0.0000e+00,  6.8093e-01,
        -3.5624e-01,  0.0000e+00,  3.2302e-02, -4.2100e-03,  2.3124e-02,
        -2.2767e-01, -6.6230e-01,  0.0000e+00,  5.4395e-01,  1.2575e+00,
         6.0546e-01, -1.2386e-01,  5.1282e-01,  0.0000e+00, -5.0374e-01,
        -2.0934e-01,  1.6390e-01,  1.9552e-01,  8.7618e-02, -1.1469e+00,
        -3.1720e-01,  6.2132e-02,  3.3133e-01, -2.5122e-02, -3.4593e-02,
        -6.5851e-01,  4.2816e-04, -7.2423e-02, -6.5629e-01, -2.1883e-01,
        -1.4935e-01,  8.9773e-01, -1.5623e-01,  0.0000e+00,  2.4546e-02,
        -3.5709e-01, -9.4222e-01, -1.1718e-01, -6.1813e-01, -1.7652e-01,
         1.0460e-01, -6.2822e-01, -3.6749e-01, -1.8878e-01, -2.6630e-01,
        -5.2445e-01,  7.6502e-02, -1.0615e-01, -1.6425e-01, -4.0413e-01,
        -7.2657e-01, -3.3089e-01,  3.7161e-02, -8.1525e-01,  1.3346e-01,
        -9.9192e-01,  2.9311e-01,  2.4566e-01,  6.3414e-01,  1.7033e-01,
        -4.4184e-01, -2.0106e-01, -3.8979e-03,  0.0000e+00, -7.9384e-02,
        -1.3757e-02, -3.2263e-01, -6.8126e-01, -1.6517e-01, -1.5155e-01,
         1.8087e-01, -2.6300e-01,  1.4201e-01, -2.0741e-01, -5.1845e-01,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00]), tensor([5678]), tensor(0.2117))
INFO:main.py:Create prediction_dataset
INFO:main.py:prediction_dataset first example: (tensor([-9.6036e-01, -4.9283e-01, -4.7202e-01, -1.2875e+00, -5.9088e-01,
        -3.4143e-01, -1.7353e+00, -1.0156e+00,  6.0711e-02,  1.9547e-01,
        -4.0377e-01, -9.2351e-03, -4.1386e-03, -3.5552e-02,  1.6291e-02,
         4.4557e-03, -4.1867e-01,  1.1388e-02,  0.0000e+00, -2.8223e-01,
        -1.5983e-01,  0.0000e+00,  8.3143e-02,  4.9025e-02, -1.0656e-02,
        -6.2313e-01, -8.2264e-01,  0.0000e+00, -5.7750e-01,  1.3797e+00,
        -1.6007e+00, -3.2115e-01,  1.1211e-01,  0.0000e+00, -1.0634e+00,
         3.8040e-03, -5.2228e-01, -8.2825e-01, -2.7243e-01, -8.6950e-01,
         5.3128e-01, -8.5044e-01, -3.8617e-01, -2.6063e-01, -4.5432e-01,
        -1.9406e-01,  1.0492e-02, -3.0692e-01,  5.1011e-03, -9.7349e-03,
        -8.4332e-01, -1.1018e+00, -1.1294e+00,  0.0000e+00, -8.6923e-01,
        -9.1403e-01,  2.6640e-02, -1.2260e-01, -3.3319e-01, -3.9018e-02,
        -1.9560e-01, -3.4380e-01, -1.7398e-01,  3.2079e-01, -1.7674e-03,
        -4.6619e-01, -2.1413e-01,  1.4636e+00, -8.8986e-01, -3.8259e-01,
        -9.5638e-03, -3.3089e-02,  3.7161e-02,  3.0098e-02, -4.4583e-01,
        -7.1099e-02, -3.4420e-01,  8.4362e-02, -6.3088e-01, -2.8029e-01,
         4.2441e+00,  3.3876e-01, -3.8979e-03,  0.0000e+00, -7.6692e-01,
        -6.3231e-02,  2.3258e+00,  5.0224e+00, -3.6348e-02, -4.6659e-02,
         2.0041e-01, -8.0320e-01, -4.0666e-01,  3.0623e-01,  1.1257e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00]), tensor([778]), tensor(0.0638))
INFO:main.py:train and test dataloader
INFO:main.py:train_loader first example: [tensor([[-1.0088e+00, -5.4216e-01, -4.3827e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-6.9240e-01, -2.8173e-01, -2.2381e-03,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-2.1133e-01,  1.1428e-01, -3.3944e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 4.2181e+00,  3.3445e+00, -9.9015e-01,  ...,  1.0000e+00,
          1.0000e+00,  0.0000e+00],
        [-2.6579e-01,  6.9446e-02,  2.2379e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-5.0509e-01, -1.2754e-01, -3.0765e-01,  ...,  1.0000e+00,
          1.0000e+00,  0.0000e+00]]), tensor([[  23],
        [4143],
        [2778],
        [2498],
        [ 987],
        [3546],
        [3779],
        [3984],
        [ 379],
        [4753],
        [4847],
        [1560],
        [3825],
        [5693],
        [4864],
        [3641],
        [3901],
        [4934],
        [4525],
        [ 976],
        [3289],
        [2274],
        [4517],
        [ 323],
        [6634],
        [6423],
        [3566],
        [5709],
        [2828],
        [ 340],
        [2265],
        [ 674]]), tensor([ 0.0655, -0.0700,  0.0394,  0.0787,  0.1803, -0.0815, -0.2308,  0.0750,
         0.0774,  0.0566,  0.1026,  0.0150, -0.0853, -0.0414,  0.0484,  0.0000,
         0.1579,  0.1905,  0.0409, -0.0023, -0.0377,  0.3750, -0.0077,  0.0000,
         0.0371,  0.0653,  0.2111,  0.0000, -0.1364,  0.0000, -0.0100,  0.1071])]

INFO:main.py:test_loader first example: [tensor([[-6.9920e-03,  8.9557e-03, -3.4033e-01,  ...,  0.0000e+00,
          1.0000e+00,  0.0000e+00],
        [-6.9920e-03,  8.9557e-03, -6.7673e-04,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-6.9920e-03,  8.9557e-03,  1.0606e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [-3.9113e-01, -3.3732e-02, -8.1276e-01,  ...,  0.0000e+00,
          1.0000e+00,  1.0000e+00],
        [-9.6154e-01, -5.0328e-01, -6.0189e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 3.6633e+00,  3.3038e+00,  1.8561e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]]), tensor([[3934],
        [1253],
        [ 674],
        [1247],
        [2800],
        [3015],
        [3071],
        [2783],
        [2358],
        [3629],
        [2060],
        [3375],
        [3553],
        [1969],
        [2125],
        [1259],
        [4952],
        [1722],
        [2536],
        [4893],
        [1613],
        [ 295],
        [ 121],
        [3973],
        [3152],
        [ 719],
        [3167],
        [2545],
        [4426],
        [1910],
        [2826],
        [1095]]), tensor([-0.5200,  0.0000, -0.0217,  0.0909,  0.0417, -0.2105,  0.1136,  0.3243,
         0.0667,  0.2500,  0.1060,  0.1562,  0.4306,  0.1304, -0.0133, -0.0222,
        -0.2667, -0.1571,  0.1707,  0.0667,  0.0847,  0.1776,  0.2695,  0.0476,
         0.1163,  0.2268, -0.1351,  0.0000,  0.3103,  0.1769,  0.1379,  0.2647])]

INFO:main.py:retrain and prediction dataloader
INFO:main.py:retrain_loader first example: [tensor([[-6.4251e-01, -2.3176e-01, -1.2428e-02,  ...,  0.0000e+00,
          1.0000e+00,  0.0000e+00],
        [ 6.6112e-03, -8.9386e-04,  1.0027e-01,  ...,  0.0000e+00,
          1.0000e+00,  0.0000e+00],
        [-1.1822e+00, -7.7625e-01,  4.7390e-02,  ...,  0.0000e+00,
          1.0000e+00,  0.0000e+00],
        ...,
        [ 1.7761e+00,  1.7547e+00,  7.9389e-03,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-4.8290e-01, -1.0067e-01,  1.6989e+00,  ...,  0.0000e+00,
          1.0000e+00,  0.0000e+00],
        [ 5.6217e-03, -3.3511e-03, -8.8565e-01,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]]), tensor([[2872],
        [4741],
        [4879],
        [7213],
        [2287],
        [6120],
        [5521],
        [ 817],
        [5674],
        [3333],
        [6127],
        [6461],
        [6097],
        [1736],
        [3878],
        [1458],
        [3996],
        [ 618],
        [6960],
        [ 973],
        [ 150],
        [1940],
        [4166],
        [4859],
        [3185],
        [5012],
        [5663],
        [3777],
        [5849],
        [3993],
        [2398],
        [6712]]), tensor([-0.0385,  0.0476, -0.1154,  0.0000,  0.3143,  0.3333,  0.2000,  0.1145,
         0.1567,  0.1346,  0.0615, -0.1176,  0.1224, -0.0654,  0.1617,  0.0000,
         0.0312,  0.0342, -0.0789,  0.3538,  0.1223,  0.0124,  0.1680,  0.0000,
         0.1739, -0.0413, -0.0680,  0.0992,  0.0638, -0.1042,  0.0435,  0.0425])]

INFO:main.py:prediction_loader first example: [tensor([[-0.9604, -0.4928, -0.4720,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0053,  0.0067,  3.1135,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0053,  0.0067, -0.1770,  ...,  0.0000,  1.0000,  0.0000],
        ...,
        [ 0.0554,  0.3415, -0.3227,  ...,  0.0000,  1.0000,  0.0000],
        [-0.0053,  0.0067, -0.3629,  ...,  0.0000,  1.0000,  0.0000],
        [-0.0053,  0.0067,  1.4540,  ...,  0.0000,  1.0000,  0.0000]]), tensor([[ 778],
        [2589],
        [3797],
        [ 142],
        [4114],
        [5241],
        [1143],
        [5223],
        [4162],
        [4863],
        [2121],
        [ 723],
        [1599],
        [1996],
        [1331],
        [5078],
        [2924],
        [2942],
        [4798],
        [5035],
        [3479],
        [4811],
        [5114],
        [3169],
        [ 830],
        [3227],
        [2925],
        [ 563],
        [1675],
        [2483],
        [3588],
        [1915]]), tensor([ 0.0638,  0.1111,  0.1190, -0.0606,  0.0769,  0.0467, -0.0147, -0.1111,
        -0.0345,  0.0000, -0.1304, -0.0476,  0.0682,  0.0517,  0.2500, -0.1176,
        -0.0357,  0.0000,  0.2500,  0.2075, -0.3333,  0.0000, -0.0909, -0.3077,
         0.1212, -0.0556,  0.2353, -0.1923, -0.0952, -0.0845,  0.6875,  0.0800])]

INFO:main.py:Hyperparameters tuning with Ray Tune
INFO:main.py:Training data years: [1980, 1981, 1982, 1983, 1984, 1985, 1986]
INFO:main.py:Testing data year: 1987
2024-07-02 21:13:03,492	INFO worker.py:1753 -- Started a local Ray instance.
2024-07-02 21:13:03,516	INFO packaging.py:530 -- Creating a file package for local directory '/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/src'.
2024-07-02 21:13:03,536	INFO packaging.py:358 -- Pushing file package 'gcs://_ray_pkg_5ffdcf573b253121.zip' (1.19MiB) to Ray cluster...
2024-07-02 21:13:03,542	INFO packaging.py:371 -- Successfully pushed file package 'gcs://_ray_pkg_5ffdcf573b253121.zip'.
2024-07-02 21:13:05,547	WARNING tune.py:902 -- AIR_VERBOSITY is set, ignoring passed-in ProgressReporter for now.
2024-07-02 21:13:15,432	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00006
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918774, ip=10.112.2.40, actor_id=446d9f0af71f6d925b38d65b01000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,462	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00015
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918975, ip=10.112.2.40, actor_id=c15878963828b472347b863601000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,541	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00009
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918825, ip=10.112.2.40, actor_id=f5e7cf9bfbf4af46ae078c6201000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,590	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00014
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918953, ip=10.112.2.40, actor_id=6bc783edbdbb74d73b18cc4d01000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,606	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00013
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918893, ip=10.112.2.40, actor_id=88d9b66fb43d50c30a4325f401000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,621	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00000
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918687, ip=10.112.2.40, actor_id=2a68c445191a0d10433d931c01000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,660	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00007
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918791, ip=10.112.2.40, actor_id=f3063260690a30d1cc34fed501000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,699	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00004
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918756, ip=10.112.2.40, actor_id=e94817eb570ecd189bd1bcdc01000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,703	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00017
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918993, ip=10.112.2.40, actor_id=7ec13dc57f46938118bf744201000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,740	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00001
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918688, ip=10.112.2.40, actor_id=a955091c877cf5975b39159201000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,756	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00003
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918723, ip=10.112.2.40, actor_id=601c03a59817811ac823ab9d01000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,766	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00019
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918995, ip=10.112.2.40, actor_id=3f5037a9a8c0c233601d3f5f01000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,770	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00002
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918705, ip=10.112.2.40, actor_id=6c016e9f0821383e5243056701000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,782	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00010
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918890, ip=10.112.2.40, actor_id=c90e87e70cc52eddbb94d46201000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,793	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00005
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918757, ip=10.112.2.40, actor_id=1675e868b17589b088178d9101000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,799	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00008
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918808, ip=10.112.2.40, actor_id=9680eeac0262f64fb197a35501000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,802	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00018
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918994, ip=10.112.2.40, actor_id=2fea4bf0353d8800d8323fb101000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,804	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00016
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918976, ip=10.112.2.40, actor_id=b4f389d43ee865e0d9ef994701000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,810	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00011
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918891, ip=10.112.2.40, actor_id=18f3d61a02e8eb45d65b5d5301000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,812	ERROR tune_controller.py:1331 -- Trial task failed for trial train_fnn_dfb4f_00012
Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=2918892, ip=10.112.2.40, actor_id=c8d2fdc5b3bf997abb03635601000000, repr=train_fnn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
  File "/tmp/ray/session_2024-07-02_21-12-59_226018_2914170/runtime_resources/working_dir_files/_ray_pkg_5ffdcf573b253121/model_data_nn.py", line 157, in train_fnn
    model.to(device)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
2024-07-02 21:13:15,901	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/ray_results/train_fnn_2024-07-02_21-13-05' in 0.0873s.
╭──────────────────────────────────────────────────────────────────╮
│ Configuration for experiment     train_fnn_2024-07-02_21-13-05   │
├──────────────────────────────────────────────────────────────────┤
│ Search algorithm                 BasicVariantGenerator           │
│ Scheduler                        AsyncHyperBandScheduler         │
│ Number of trials                 20                              │
╰──────────────────────────────────────────────────────────────────╯

View detailed results here: /zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/ray_results/train_fnn_2024-07-02_21-13-05
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts`

Trial status: 20 PENDING
Current time: 2024-07-02 21:13:05. Total running time: 0s
Logical resource usage: 0/40 CPUs, 0/2 GPUs (0.0/1.0 accelerator_type:A30)
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Trial name              status       hidden_dim     num_layers     embedding_dim     dropout_rate            lr     weight_decay │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ train_fnn_dfb4f_00000   PENDING              65              4                36        0.423074    4.20799e-06      2.93754e-06 │
│ train_fnn_dfb4f_00001   PENDING              35              3                26        0.048924    0.000772672      0.000654121 │
│ train_fnn_dfb4f_00002   PENDING               5              4                46        0.372082    5.34294e-05      7.47631e-06 │
│ train_fnn_dfb4f_00003   PENDING              95              4                11        0.273899    0.00856887       2.51356e-05 │
│ train_fnn_dfb4f_00004   PENDING              65              5                41        0.0548856   0.00624514       0.000788671 │
│ train_fnn_dfb4f_00005   PENDING              85              2                21        0.169317    9.20665e-06      0.000112148 │
│ train_fnn_dfb4f_00006   PENDING              75              3                 1        0.188558    0.000446775      8.61258e-06 │
│ train_fnn_dfb4f_00007   PENDING              95              4                26        0.0316062   0.00233959       2.23492e-05 │
│ train_fnn_dfb4f_00008   PENDING              35              4                41        0.673209    0.00238856       0.000174566 │
│ train_fnn_dfb4f_00009   PENDING             125              1                 1        0.0207891   4.93862e-05      1.52983e-05 │
│ train_fnn_dfb4f_00010   PENDING             105              3                 1        0.500826    0.00144778       6.57476e-05 │
│ train_fnn_dfb4f_00011   PENDING              85              4                31        0.596527    6.27773e-05      1.93299e-06 │
│ train_fnn_dfb4f_00012   PENDING              45              3                36        0.199558    0.000175782      1.40858e-05 │
│ train_fnn_dfb4f_00013   PENDING              25              1                21        0.397281    0.00121302       3.02961e-05 │
│ train_fnn_dfb4f_00014   PENDING             145              2                46        0.313142    6.41028e-06      0.000486733 │
│ train_fnn_dfb4f_00015   PENDING              35              5                31        0.427048    0.000144333      4.06615e-06 │
│ train_fnn_dfb4f_00016   PENDING              65              3                11        0.121243    0.00523348       0.000265681 │
│ train_fnn_dfb4f_00017   PENDING              55              4                16        0.625866    0.000143671      0.000264436 │
│ train_fnn_dfb4f_00018   PENDING              65              1                 1        0.167275    5.11012e-05      0.000284475 │
│ train_fnn_dfb4f_00019   PENDING              65              3                41        0.344533    0.000588497      6.43039e-06 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00002 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00002 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.37208 │
│ embedding_dim                               46 │
│ hidden_dim                                   5 │
│ lr                                       5e-05 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                             1e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00014 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00014 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.31314 │
│ embedding_dim                               46 │
│ hidden_dim                                 145 │
│ lr                                       1e-05 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   2 │
│ weight_decay                           0.00049 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00015 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00015 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.42705 │
│ embedding_dim                               31 │
│ hidden_dim                                  35 │
│ lr                                     0.00014 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   5 │
│ weight_decay                                 0 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00006 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00006 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.18856 │
│ embedding_dim                                1 │
│ hidden_dim                                  75 │
│ lr                                     0.00045 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   3 │
│ weight_decay                             1e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00010 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00010 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.50083 │
│ embedding_dim                                1 │
│ hidden_dim                                 105 │
│ lr                                     0.00145 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   3 │
│ weight_decay                             7e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00011 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00011 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.59653 │
│ embedding_dim                               31 │
│ hidden_dim                                  85 │
│ lr                                       6e-05 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                                 0 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00008 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00008 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.67321 │
│ embedding_dim                               41 │
│ hidden_dim                                  35 │
│ lr                                     0.00239 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                           0.00017 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00005 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00005 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.16932 │
│ embedding_dim                               21 │
│ hidden_dim                                  85 │
│ lr                                       1e-05 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   2 │
│ weight_decay                           0.00011 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00003 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00003 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                            0.2739 │
│ embedding_dim                               11 │
│ hidden_dim                                  95 │
│ lr                                     0.00857 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                             3e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00007 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00007 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.03161 │
│ embedding_dim                               26 │
│ hidden_dim                                  95 │
│ lr                                     0.00234 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                             2e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00009 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00009 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.02079 │
│ embedding_dim                                1 │
│ hidden_dim                                 125 │
│ lr                                       5e-05 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   1 │
│ weight_decay                             2e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00000 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00000 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.42307 │
│ embedding_dim                               36 │
│ hidden_dim                                  65 │
│ lr                                           0 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                                 0 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00013 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00013 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.39728 │
│ embedding_dim                               21 │
│ hidden_dim                                  25 │
│ lr                                     0.00121 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   1 │
│ weight_decay                             3e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00016 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00016 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.12124 │
│ embedding_dim                               11 │
│ hidden_dim                                  65 │
│ lr                                     0.00523 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   3 │
│ weight_decay                           0.00027 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00004 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00004 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.05489 │
│ embedding_dim                               41 │
│ hidden_dim                                  65 │
│ lr                                     0.00625 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   5 │
│ weight_decay                           0.00079 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00017 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00017 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.62587 │
│ embedding_dim                               16 │
│ hidden_dim                                  55 │
│ lr                                     0.00014 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   4 │
│ weight_decay                           0.00026 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00001 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00001 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.04892 │
│ embedding_dim                               26 │
│ hidden_dim                                  35 │
│ lr                                     0.00077 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   3 │
│ weight_decay                           0.00065 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00018 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00018 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.16728 │
│ embedding_dim                                1 │
│ hidden_dim                                  65 │
│ lr                                       5e-05 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   1 │
│ weight_decay                           0.00028 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00019 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00019 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.34453 │
│ embedding_dim                               41 │
│ hidden_dim                                  65 │
│ lr                                     0.00059 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   3 │
│ weight_decay                             1e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00012 started with configuration:
╭────────────────────────────────────────────────╮
│ Trial train_fnn_dfb4f_00012 config             │
├────────────────────────────────────────────────┤
│ continuous_dim                             102 │
│ dropout_rate                           0.19956 │
│ embedding_dim                               36 │
│ hidden_dim                                  45 │
│ lr                                     0.00018 │
│ num_embeddings                            6642 │
│ num_epochs                                   5 │
│ num_gpus                                     2 │
│ num_layers                                   3 │
│ weight_decay                             1e-05 │
╰────────────────────────────────────────────────╯

Trial train_fnn_dfb4f_00006 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 9s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00006_6_dropout_rate=0.1886,embedding_dim=1,hidden_dim=75,lr=0.0004,num_layers=3,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00015 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 9s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00015_15_dropout_rate=0.4270,embedding_dim=31,hidden_dim=35,lr=0.0001,num_layers=5,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00009 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 9s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00009_9_dropout_rate=0.0208,embedding_dim=1,hidden_dim=125,lr=0.0000,num_layers=1,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00014 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00014_14_dropout_rate=0.3131,embedding_dim=46,hidden_dim=145,lr=0.0000,num_layers=2,weight_decay=0.0005_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00013 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00013_13_dropout_rate=0.3973,embedding_dim=21,hidden_dim=25,lr=0.0012,num_layers=1,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00000 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00000_0_dropout_rate=0.4231,embedding_dim=36,hidden_dim=65,lr=0.0000,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00007 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00007_7_dropout_rate=0.0316,embedding_dim=26,hidden_dim=95,lr=0.0023,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00004 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00004_4_dropout_rate=0.0549,embedding_dim=41,hidden_dim=65,lr=0.0062,num_layers=5,weight_decay=0.0008_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00017 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00017_17_dropout_rate=0.6259,embedding_dim=16,hidden_dim=55,lr=0.0001,num_layers=4,weight_decay=0.0003_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00001 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00001_1_dropout_rate=0.0489,embedding_dim=26,hidden_dim=35,lr=0.0008,num_layers=3,weight_decay=0.0007_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00003 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00003_3_dropout_rate=0.2739,embedding_dim=11,hidden_dim=95,lr=0.0086,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00019 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00019_19_dropout_rate=0.3445,embedding_dim=41,hidden_dim=65,lr=0.0006,num_layers=3,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00002 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00002_2_dropout_rate=0.3721,embedding_dim=46,hidden_dim=5,lr=0.0001,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00010 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00010_10_dropout_rate=0.5008,embedding_dim=1,hidden_dim=105,lr=0.0014,num_layers=3,weight_decay=0.0001_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00005 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00005_5_dropout_rate=0.1693,embedding_dim=21,hidden_dim=85,lr=0.0000,num_layers=2,weight_decay=0.0001_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00008 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00008_8_dropout_rate=0.6732,embedding_dim=41,hidden_dim=35,lr=0.0024,num_layers=4,weight_decay=0.0002_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00018 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00018_18_dropout_rate=0.1673,embedding_dim=1,hidden_dim=65,lr=0.0001,num_layers=1,weight_decay=0.0003_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00016 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00016_16_dropout_rate=0.1212,embedding_dim=11,hidden_dim=65,lr=0.0052,num_layers=3,weight_decay=0.0003_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00011 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00011_11_dropout_rate=0.5965,embedding_dim=31,hidden_dim=85,lr=0.0001,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial train_fnn_dfb4f_00012 errored after 0 iterations at 2024-07-02 21:13:15. Total running time: 10s
Error file: /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00012_12_dropout_rate=0.1996,embedding_dim=36,hidden_dim=45,lr=0.0002,num_layers=3,weight_decay=0.0000_2024-07-02_21-13-05/error.txt

Trial status: 20 ERROR
Current time: 2024-07-02 21:13:15. Total running time: 10s
Logical resource usage: 4.0/40 CPUs, 0/2 GPUs (0.0/1.0 accelerator_type:A30)
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Trial name              status       hidden_dim     num_layers     embedding_dim     dropout_rate            lr     weight_decay │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ train_fnn_dfb4f_00000   ERROR                65              4                36        0.423074    4.20799e-06      2.93754e-06 │
│ train_fnn_dfb4f_00001   ERROR                35              3                26        0.048924    0.000772672      0.000654121 │
│ train_fnn_dfb4f_00002   ERROR                 5              4                46        0.372082    5.34294e-05      7.47631e-06 │
│ train_fnn_dfb4f_00003   ERROR                95              4                11        0.273899    0.00856887       2.51356e-05 │
│ train_fnn_dfb4f_00004   ERROR                65              5                41        0.0548856   0.00624514       0.000788671 │
│ train_fnn_dfb4f_00005   ERROR                85              2                21        0.169317    9.20665e-06      0.000112148 │
│ train_fnn_dfb4f_00006   ERROR                75              3                 1        0.188558    0.000446775      8.61258e-06 │
│ train_fnn_dfb4f_00007   ERROR                95              4                26        0.0316062   0.00233959       2.23492e-05 │
│ train_fnn_dfb4f_00008   ERROR                35              4                41        0.673209    0.00238856       0.000174566 │
│ train_fnn_dfb4f_00009   ERROR               125              1                 1        0.0207891   4.93862e-05      1.52983e-05 │
│ train_fnn_dfb4f_00010   ERROR               105              3                 1        0.500826    0.00144778       6.57476e-05 │
│ train_fnn_dfb4f_00011   ERROR                85              4                31        0.596527    6.27773e-05      1.93299e-06 │
│ train_fnn_dfb4f_00012   ERROR                45              3                36        0.199558    0.000175782      1.40858e-05 │
│ train_fnn_dfb4f_00013   ERROR                25              1                21        0.397281    0.00121302       3.02961e-05 │
│ train_fnn_dfb4f_00014   ERROR               145              2                46        0.313142    6.41028e-06      0.000486733 │
│ train_fnn_dfb4f_00015   ERROR                35              5                31        0.427048    0.000144333      4.06615e-06 │
│ train_fnn_dfb4f_00016   ERROR                65              3                11        0.121243    0.00523348       0.000265681 │
│ train_fnn_dfb4f_00017   ERROR                55              4                16        0.625866    0.000143671      0.000264436 │
│ train_fnn_dfb4f_00018   ERROR                65              1                 1        0.167275    5.11012e-05      0.000284475 │
│ train_fnn_dfb4f_00019   ERROR                65              3                41        0.344533    0.000588497      6.43039e-06 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Number of errored trials: 20
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Trial name                # failures   error file                                                                                                                                                                                                                                                                             │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ train_fnn_dfb4f_00000              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00000_0_dropout_rate=0.4231,embedding_dim=36,hidden_dim=65,lr=0.0000,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00001              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00001_1_dropout_rate=0.0489,embedding_dim=26,hidden_dim=35,lr=0.0008,num_layers=3,weight_decay=0.0007_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00002              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00002_2_dropout_rate=0.3721,embedding_dim=46,hidden_dim=5,lr=0.0001,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt    │
│ train_fnn_dfb4f_00003              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00003_3_dropout_rate=0.2739,embedding_dim=11,hidden_dim=95,lr=0.0086,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00004              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00004_4_dropout_rate=0.0549,embedding_dim=41,hidden_dim=65,lr=0.0062,num_layers=5,weight_decay=0.0008_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00005              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00005_5_dropout_rate=0.1693,embedding_dim=21,hidden_dim=85,lr=0.0000,num_layers=2,weight_decay=0.0001_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00006              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00006_6_dropout_rate=0.1886,embedding_dim=1,hidden_dim=75,lr=0.0004,num_layers=3,weight_decay=0.0000_2024-07-02_21-13-05/error.txt    │
│ train_fnn_dfb4f_00007              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00007_7_dropout_rate=0.0316,embedding_dim=26,hidden_dim=95,lr=0.0023,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00008              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00008_8_dropout_rate=0.6732,embedding_dim=41,hidden_dim=35,lr=0.0024,num_layers=4,weight_decay=0.0002_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00009              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00009_9_dropout_rate=0.0208,embedding_dim=1,hidden_dim=125,lr=0.0000,num_layers=1,weight_decay=0.0000_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00010              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00010_10_dropout_rate=0.5008,embedding_dim=1,hidden_dim=105,lr=0.0014,num_layers=3,weight_decay=0.0001_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00011              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00011_11_dropout_rate=0.5965,embedding_dim=31,hidden_dim=85,lr=0.0001,num_layers=4,weight_decay=0.0000_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00012              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00012_12_dropout_rate=0.1996,embedding_dim=36,hidden_dim=45,lr=0.0002,num_layers=3,weight_decay=0.0000_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00013              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00013_13_dropout_rate=0.3973,embedding_dim=21,hidden_dim=25,lr=0.0012,num_layers=1,weight_decay=0.0000_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00014              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00014_14_dropout_rate=0.3131,embedding_dim=46,hidden_dim=145,lr=0.0000,num_layers=2,weight_decay=0.0005_2024-07-02_21-13-05/error.txt │
│ train_fnn_dfb4f_00015              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00015_15_dropout_rate=0.4270,embedding_dim=31,hidden_dim=35,lr=0.0001,num_layers=5,weight_decay=0.0000_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00016              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00016_16_dropout_rate=0.1212,embedding_dim=11,hidden_dim=65,lr=0.0052,num_layers=3,weight_decay=0.0003_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00017              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00017_17_dropout_rate=0.6259,embedding_dim=16,hidden_dim=55,lr=0.0001,num_layers=4,weight_decay=0.0003_2024-07-02_21-13-05/error.txt  │
│ train_fnn_dfb4f_00018              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00018_18_dropout_rate=0.1673,embedding_dim=1,hidden_dim=65,lr=0.0001,num_layers=1,weight_decay=0.0003_2024-07-02_21-13-05/error.txt   │
│ train_fnn_dfb4f_00019              1   /tmp/ray/session_2024-07-02_21-12-59_226018_2914170/artifacts/2024-07-02_21-13-05/train_fnn_2024-07-02_21-13-05/driver_artifacts/train_fnn_dfb4f_00019_19_dropout_rate=0.3445,embedding_dim=41,hidden_dim=65,lr=0.0006,num_layers=3,weight_decay=0.0000_2024-07-02_21-13-05/error.txt  │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Traceback (most recent call last):
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/src/main.py", line 350, in <module>
    main()
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/src/main.py", line 303, in main
    best_trial = data_modeler.get_best_trial(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/src/model_data_nn.py", line 234, in get_best_trial
    result = tune.run(
  File "/zfs/projects/darc/wolee_edehaan_suzienoh-exploratory-ml/kevin/venv/lib/python3.10/site-packages/ray/tune/tune.py", line 1035, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [train_fnn_dfb4f_00000, train_fnn_dfb4f_00001, train_fnn_dfb4f_00002, train_fnn_dfb4f_00003, train_fnn_dfb4f_00004, train_fnn_dfb4f_00005, train_fnn_dfb4f_00006, train_fnn_dfb4f_00007, train_fnn_dfb4f_00008, train_fnn_dfb4f_00009, train_fnn_dfb4f_00010, train_fnn_dfb4f_00011, train_fnn_dfb4f_00012, train_fnn_dfb4f_00013, train_fnn_dfb4f_00014, train_fnn_dfb4f_00015, train_fnn_dfb4f_00016, train_fnn_dfb4f_00017, train_fnn_dfb4f_00018, train_fnn_dfb4f_00019])
